### ISSUE TITLE
Master broken!

### ISSUE THREAD

**Issue by 304NotModified** [sinairv/YAXLib#61]
Latest build from master:

https://ci.appveyor.com/project/SinaIravanian/yaxlib/build/2.13.32

```
Errors and Failures
1) Failed : YAXLibTests.DeserializationTest.DesNonGenericCollectionsSampleTest
  String lengths are both 1061. Strings differ at index 254.
  Expected: "...      Key:\r\n      [\r\n         02/01/2009 00:00:00\r\n      ]..."
  But was:  "...      Key:\r\n      [\r\n         1\r\n      ]\r\n      Value:\r\n  ..."
  ------------------------------------------------^
at YAXLibTests.DeserializationTest.PerformTestAndReturn(Object obj) in C:\xaxlib\YAXLibTests\DeserializationTest.cs:line 61
at YAXLibTests.DeserializationTest.PerformTest(Object obj) in C:\xaxlib\YAXLibTests\DeserializationTest.cs:line 40
at YAXLibTests.DeserializationTest.DesNonGenericCollectionsSampleTest() in C:\xaxlib\YAXLibTests\DeserializationTest.cs:line 328
Test Run Summary
  Overall result: Failed
  Test Count: 211, Passed: 210, Failed: 1, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 1, Errors: 0, Invalid: 0
  Start time: 2017-02-18 09:45:47Z
    End time: 2017-02-18 09:45:49Z
    Duration: 2.329 seconds
Results saved as C:\xaxlib\TestResult.xml
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
Command exited with code 1
```

**Comment by sinairv** [comment]
Yeah, it's the order of items in a hash-table. Since hash-table does not (and should not) guarantee the order of items, the test should be modified not to expect any particular order for items.
